name: Query RAPID API Serice using secret key and token
run-name: ${{ github.actor }} is Querying RAPID API Service using secret key and token 🚀
on: [push]
jobs:
  query-rapid-api-service:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install pip packages
        run: pip install requests
      - name: query rapidapi service
        run: python lovecal.py "$api_key" "$api_token"
        env:
          api_key: ${{ secrets.api_key }}
          api_token: ${{ secrets.api_token }}
      - name: print pass
        run: echo "$pass"
        env:
          pass: ${{ secrets.pass }}
