name: Generate OTP and Mask Data
run-name: ${{ github.actor }} is Generating OTP and Masking Data 🚀
on: [push]
jobs:
  Generate-Mask-OTP:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Generate and Mask OTP Code
        id: genotp
        run: |
          otpcode=`python -c "import otpgenerator; x = otpgenerator.generateOTP(); print(x)"`
          echo "otp code before masking : $otpcode"
          echo "::add-mask::$otpcode"
          echo "otpcode=$otpcode" >> "$GITHUB_OUTPUT"
      - name: Print OTP code after Masking
        run: |
          echo "Masked OTP Code is : ${{ steps.genotp.outputs.otpcode }}"
