name: GitHub Workflow Commands Demo
run-name: ${{ github.actor }} is testing out GitHub Workflow Commands 🚀
on: [push]
jobs:
  Explore-GitHub-Workflow-Commands:
    runs-on: ubuntu-latest
    steps:
      - name: Create annotation for build error
        run: echo "::error file=app.js,line=1::Missing semicolon"
      - name: Create a notification message
        run: echo "::notice file=hello-runner.sh,line=1,endLine=7,title=hello-runner::shebang line"
      - name: Create a warning message
        run: echo "::warning file=hello-runner.sh,line=1,endLine=7,title=hello-runner::shebang line"
      - name: Masking a Secret value
        run: echo "::add-mask::${{ runner.os }}"